### ISSUE TITLE
PTeleport_Streamer_UpdateEx

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/protection#12]
https://github.com/Open-GTO/protection/blob/c7141a26db8bb1fa462d132cdaaf4990b2d9d5d1/protection/teleport.inc#L180-L202

Есть вопрос: зачем учитывать эту функцию, если фактически она никуда не телепортирует игрока?

Также в любом случае её можно поместить под проверку:
```
#if defined PROTECTION_USE_STREAMER
//...
#endif
```
Чтобы вызывая её без стримера ошибки не летели на этот include.

И да, в новой защите "camera mode" небольшая опечатка вот тут:
```
#if !defined _protection_included
	#error "Please include protection before camera **mode**"
#endif
```

**Comment by ziggi** [comment]
Если `compensatedtime` в `Streamer_UpdateEx` не равен -1, то эта функция устанавливает позицию игрока.

Это поведение [задокументировано](https://github.com/samp-incognito/samp-streamer-plugin/wiki/Natives-(Updates)#Streamer_UpdateEx):
> If `compensatedtime` is set to a positive number, it can be used to specify how long, in milliseconds, future automatic updates will be paused for the player. During this time, the player's controls will be disabled (assuming `freezeplayer` is set to `1`), and the player's position will also be set to the new coordinates.

Остальное поправил, спасибо.
