### ISSUE TITLE
Античит на оружие некорректно устанавливает реальное оружие

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/protection#15]
https://github.com/Open-GTO/protection/blob/8fe34053ff70adc7f7fb5b8cae69ea7d3924cb0b/protection/weapon.inc#L258-L264

Как видно из названия и кода выше, это не работает, к примеру, если игрок не имел оружия в одном из слотов и вдруг в нём какое-то начитерил (банально взять стандартный собейт и выбрать вкладку "Weapons" для проверки). И это также не будет правильно работать (и наоборот вместе с тем даёт обход на легальный чит патронов), если я, имея оружие с меньшим количеством патронов начитерю в этот слот аналогичное оружие с большим количеством патронов. Как вариант, нужно также обнулять и патроны от предыдущего начитерённого и учитывать все возможные случаи, подобные тем что выше.

**Comment by ziggi** [comment]
> Как видно из названия и кода выше, это не работает, к примеру, если игрок не имел оружия в одном из слотов и вдруг в нём какое-то начитерил (банально взять стандартный собейт и выбрать вкладку "Weapons" для проверки).

Согласен.

> И это также не будет правильно работать (и наоборот вместе с тем даёт обход на легальный чит патронов), если я, имея оружие с меньшим количеством патронов начитерю в этот слот аналогичное оружие с большим количеством патронов. Как вариант, нужно также обнулять и патроны от предыдущего начитерённого и учитывать все возможные случаи, подобные тем что выше.

Вот тут не понял. Проверка на количество патрон идёт ниже.

**Comment by NexiusTailer** [comment]
> Вот тут не понял. Проверка на количество патрон идёт ниже.

А, эт кажется я уже не заметил, что проверка на патроны не под else if, а под if идёт)
Тогда со вторым вроде как всё нормально. Странно только, что при тесте я смог спокойно начитерить оружие с патронами (Sawn-off shotgun) и ни оружие, ни патроны при этом не обнулялись.

**Comment by ziggi** [comment]
Да проверку на оружие нужно будет сильно переделывать, ибо, как оказалось, GetPlayerWeapon иногда может вернуть 0, даже если оружие в руках есть.
Возможно более надёжнее будет делать проверку в OnPlayerWeaponShot.
