### ISSUE TITLE
Падение под карту и анти-телепорт

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/protection#16]
Кстати, давно ещё хотел написать о том, что не учтен телепорт игрой на поверхность после падения игрока под карту.

**Comment by ziggi** [comment]
А как это учесть? Проверкой на высоту (colandreas, mapandreas)?

**Comment by NexiusTailer** [comment]
Как это учтено в vehicleteleport.inc: если старая z-координата < ~(-90.0) - ~(-95.0), то уже есть вероятность, что игрок только что из-под карты.
