### ISSUE TITLE
Проверка на высоту при выходе из самолёта/вертолёта

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/protection#2]
В античите на оружие [есть проверка](https://github.com/Open-GTO/protection/blob/master/protection/weapon.inc#L301) на высоту, когда игрок выходит из летательного средства, чтобы дать ему парашют. Так вот, при попытке сделать это над карьером в лв (либо в месте, где уровень земли ниже, чем -20 - -30 метров) на высоте примерно в 45 - 50 метров - парашют выдастся, проверка сработает ложно.
Нужно либо уменьшить это значение, либо убрать вообще, т.к. расчёт высоты, очевидно, идёт в зависимости от уровня земли до игрока, а не просто через фиксированное значение.

Кстати, почему бы не выложить эту защиту на форумы? :)
Некоторые античиты здесь реализованы довольно оригинально

**Comment by NexiusTailer** [comment]
Кстати, почему бы не выложить эту защиту на форумы? :)
Некоторые античиты здесь реализованы довольно оригинально

**Comment by ziggi** [comment]
По моим наблюдениям, парашют выдаётся на любой высоте, если за время полёта высота хоть раз превышала ~55.0. Просто ещё не успел это поправить и изучить.

> Кстати, почему бы не выложить эту защиту на форумы? :)
> Некоторые античиты здесь реализованы довольно оригинально

Не готово ещё, всё довольно сырое :)

**Comment by NexiusTailer** [comment]
Нет, я не превысил эту высоту, во всяком случае, после этого я поменял транспорт и попробовал снова.
