### ISSUE TITLE
OnPlayerInteriorChange isn't properly hooked.

### ISSUE THREAD

**Issue by CantBeKarma** [Open-GTO/protection#20]
This:

```
#if defined Interior_OnPlayerInteriorChange
	return Interior_OnPlayerInteriorChange(playerid, newinteriorid, oldinteriorid);
#else
```

Should be:

```
#if defined PInterio_OnPlayerInteriorChange
	return PInterio_OnPlayerInteriorChange(playerid, newinteriorid, oldinteriorid);
#else
```

As it's defined here:

```
#if defined _ALS_OnPlayerInteriorChange
	#undef OnPlayerInteriorChange
#else
	#define _ALS_OnPlayerInteriorChange
#endif

#define OnPlayerInteriorChange PInterio_OnPlayerInteriorChange
#if defined PInterio_OnPlayerInteriorChange
	forward PInterio_OnPlayerInteriorChange(playerid, newinteriorid, oldinteriorid);
#endif
```

**Comment by CantBeKarma** [comment]
Additionally, specifically in my script when I'm loading player data and spawning them and then setting their virtual world and position through a different function (rather than during OnPlayerSpawn); the code decides to reset the player's interior under the hooked OnPlayerSpawn. It must be a specific case (mine), however I don't think it hurts merely adding a check to see if someone's interior was set within the last 3 seconds and avoid resetting it to 0 under OnPlayerSpawn! (here's my code: https://pastebin.com/w37VWvcE)

I tested my own code of course and my issue vanished.

**Comment by ziggi** [comment]
Where are you using SetPlayerInterior?

**Comment by CantBeKarma** [comment]
Under my login function, after authenticating properly I've got this (which spawns the player):

```
SetSpawnInfo(playerid, 0, PlayerInfo[playerid][p_skin], PlayerInfo[playerid][p_posx], PlayerInfo[playerid][p_posy], PlayerInfo[playerid][p_posz], PlayerInfo[playerid][p_fa], -1, -1, -1, -1, -1, -1);
TogglePlayerSpectating(playerid, false); 
```

Afterwards, I call a function that handles setting the player's interior/virtual world and position:

```
SetPlayerPos(playerid, PlayerInfo[playerid][p_posx], PlayerInfo[playerid][p_posy], PlayerInfo[playerid][p_posz]);
SetPlayerFacingAngle(playerid, PlayerInfo[playerid][p_fa]);
SetPlayerVirtualWorld(playerid, PlayerInfo[playerid][p_virtualworld]);
SetPlayerInterior(playerid, PlayerInfo[playerid][p_interior]);
SetCameraBehindPlayer(playerid);
```

And basically, it calls OnPlayerSpawn AFTER my function (OnPlayerSpawn execution time seems to be a couple seconds slower than the function call) and triggers a Protection Warning (and se because you hooked OnPlayerSpawn to reset ``gPlayerInterior{playerid}`` to 0. The adjusted code in the pastebin I posted fixed this issue for me. The idea is to basically avoid resetting ``gPlayerInterior{playerid}`` if it was recently altered (using **SetPlayerInterior**) to avoid the problem caused on my server because of this. I integrated this system into a live server of mine and basically it messed up my logging in process when players logged out inside of an interior because it'd reset their interior to 0. I never enabled this protection and it took a while to realize it's forcefully enabled when you use ``DisableInteriorEnterExits();``; which is FINE, except this should be extremely solid with safe checks built into the code.

**Comment by ziggi** [comment]
I just want to find a more proper solution. Can you check this issue for a health? Add to these:
```Pawn
SetPlayerPos(playerid, PlayerInfo[playerid][p_posx], PlayerInfo[playerid][p_posy], PlayerInfo[playerid][p_posz]);
SetPlayerFacingAngle(playerid, PlayerInfo[playerid][p_fa]);
SetPlayerVirtualWorld(playerid, PlayerInfo[playerid][p_virtualworld]);
SetPlayerInterior(playerid, PlayerInfo[playerid][p_interior]);
SetCameraBehindPlayer(playerid);
```
this: 
```Pawn
SetPlayerHealth(playerid, 50.0);
```
and remove any `SetPlayerHealth` from your `OnPlayerSpawn`

**Comment by CantBeKarma** [comment]
The issue isn't a thing with Health (using **SetPlayerHealth**). It works perfectly fine.

**Comment by ziggi** [comment]
> The issue isn't a thing with Health (using SetPlayerHealth). It works perfectly fine.

My bad.

Can you check with my solution?

**Comment by CantBeKarma** [comment]
> 
> 
> > The issue isn't a thing with Health (using SetPlayerHealth). It works perfectly fine.
> 
> My bad.
> 
> Can you check with my solution?

Your solution works perfectly fine, admittedly a better fix than mine. Thanks!

**Comment by ziggi** [comment]
Thanks for reporting and helping with it.
