### ISSUE TITLE
[SUGGESTION]: Add an option to toggle off countermeasures.

### ISSUE THREAD

**Issue by CantBeKarma** [Open-GTO/protection#21]
By default, countermeasures are taking to "undo" the cheats that players do. Such as, for example, player health. If it detects that you're cheating and triggers a warning to ``OnPlayerGetProtectionWarning`` then it will set the player's health BACK to what it SHOULD be. That's fine and all, but it'd be pretty neat if we can toggle that off.

Why? Well. It'd be extremely helpful when testing (especially with new detections). That way, I can freely have basically all of the detections enabled without worrying about breaking my script (since it'll just print warnings and NOT do anything to the player).

I noticed a bug with Teleport in the past and immediately had to take it off of my live server because it'd set the player's position back to what the script knows is the last valid point they were set to (via ``SetPlayerPos``).

For Example:
``Protection_SetParamInt(PROTECTION_TELEPORT, PROTECTION_COUNTERMEASURE, 0);``

By default, countermeasures should be enabled though. Leave it up to the scripter if he wants to disable it.

**Comment by ziggi** [comment]
Agreed. I will make it in near time.

By the way, teleport protection fixed and now works fine.

**Comment by CantBeKarma** [comment]
Sweet. As for the teleport detection, I believe I was having issues under the same circumstances as the interior issue.

I'll have to do some testing to be able to determine exactly when/how the issue occurs though. I do remember the fix was to use SetSpawnInfo (to the specific cords later used for SetPlayerPos) prior to TogglePlayerSpectate. Which suggests the variables reset during the OnPlayerSpawn hook exactly like the interior issue.

**Comment by ziggi** [comment]
Done.
