### ISSUE TITLE
Прибавление пинга к временной разнице между выстрелами в rapidfire.inc

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/protection#9]
Стало интересно, зачем [прибавляется пинг в проверке на рапид](https://github.com/Open-GTO/protection/blob/1f1ebd5a807fec1c3983619fd1374c83532e53ec/protection/rapidfire.inc#L95). Ведь насколько известно, на шотрейт может влиять как минимум фпс и как максимум единоразовый лаг или что-то вроде того (потеря пакетов, перегруженность сервера ещё как варианты).
Пинг в этом плане представляет собой просто отставание, с которым все данные чуть запаздывают, но приходят ведь всё равно они довольно стабильно.
Убирать оттуда пинг я не призываю, а лишь хочу поинтересоваться, какой за этим стоит практический смысл?

P.s. И да, раз идёт проверка только в OnPlayerWeaponShot, то и массив с рейтами на всё оружие не нужен, достаточно хранить данные только для огнестрельного оружия.

**Comment by ziggi** [comment]
> Стало интересно, зачем прибавляется пинг в проверке на рапид. Ведь насколько известно, на шотрейт может влиять как минимум фпс и как максимум единоразовый лаг или что-то вроде того (потеря пакетов, перегруженность сервера ещё как варианты).
Пинг в этом плане представляет собой просто отставание, с которым все данные чуть запаздывают, но приходят ведь всё равно они довольно стабильно.
Убирать оттуда пинг я не призываю, а лишь хочу поинтересоваться, какой за этим стоит практический смысл?

Ну да, наверное смысла в этом нет. Гораздо больше смысла будет в определении среднего времени между, например, 5 выстрелами.

> P.s. И да, раз идёт проверка только в OnPlayerWeaponShot, то и массив с рейтами на всё оружие не нужен, достаточно хранить данные только для огнестрельного оружия.

Да, но с массивом для всего оружия я могу получить значение по weaponid в качестве ячейки массива, без дополнительных вычислений.

**Comment by ynhhoJ** [comment]
Rapid Fire срабатывает ложно на Deagle.
_max_shot_time_ слишком высок, поскольку пока прицел не пришел в изначальном размере, можно еще раз выстрелить.
Если 
```pawn
950, // 24 - WEAPON_DEAGLE
```
заменить на
```pawn
715, // 24 - WEAPON_DEAGLE
```
Будeт меньше ложных срабатываний.

**Comment by ziggi** [comment]
Скорость зависит от скилла, надо будет учитывать это тоже.
